Indicadores-Economicos/Indicadores-Economicos/Controllers/CompraDolarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;

namespace Indicadores_Economicos.Controllers
{
    public class CompraDolarController : Controller
    {
        // GET: CompraDolar
        public ActionResult Index()
        {
            cr.fi.bccr.gee.wsIndicadoresEconomicos cliente = new cr.fi.bccr.gee.wsIndicadoresEconomicos();
            DataSet tipoCambioVenta = cliente.ObtenerIndicadoresEconomicos("317", "15/01/2014", "15/03/2019", "Felipe Ramirez", "N");
            //ViewBag.indicador = "Código indicador: " + tipoCambioVenta.Tables[0].Rows[0].ItemArray[0].ToString();
            //ViewBag.fecha = "Fecha consultada: " + tipoCambioVenta.Tables[0].Rows[0].ItemArray[1].ToString();
            ViewBag.valor = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[0].ItemArray[2]);
            ViewBag.valor2 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[31].ItemArray[2]);
            ViewBag.valor3 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[59].ItemArray[2]);
            ViewBag.valor4 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[90].ItemArray[2]);
            ViewBag.valor5 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[120].ItemArray[2]);
            ViewBag.valor6 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[151].ItemArray[2]);
            ViewBag.valor7 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[181].ItemArray[2]);
            ViewBag.valor8 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[212].ItemArray[2]);
            ViewBag.valor9 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[243].ItemArray[2]);
            ViewBag.valor10 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[273].ItemArray[2]);
            ViewBag.valor11 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[304].ItemArray[2]);
            ViewBag.valor12 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[334].ItemArray[2]);
            ViewBag.valor13 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[365].ItemArray[2]);
            ViewBag.valor14 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[396].ItemArray[2]);
            ViewBag.valor15 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[424].ItemArray[2]);
            ViewBag.valor16 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[455].ItemArray[2]);
            ViewBag.valor17 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[485].ItemArray[2]);
            ViewBag.valor18 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[516].ItemArray[2]);
            ViewBag.valor19 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[546].ItemArray[2]);
            ViewBag.valor20 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[577].ItemArray[2]);
            ViewBag.valor21 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[608].ItemArray[2]);
            ViewBag.valor22 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[638].ItemArray[2]);
            ViewBag.valor23 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[669].ItemArray[2]);
            ViewBag.valor24 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[699].ItemArray[2]);
            ViewBag.valor25 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[730].ItemArray[2]);
            ViewBag.valor26 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[761].ItemArray[2]);
            ViewBag.valor27 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[790].ItemArray[2]);
            ViewBag.valor28 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[821].ItemArray[2]);
            ViewBag.valor29 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[851].ItemArray[2]);
            ViewBag.valor30 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[882].ItemArray[2]);
            ViewBag.valor31 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[912].ItemArray[2]);
            ViewBag.valor32 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[943].ItemArray[2]);
            ViewBag.valor33 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[974].ItemArray[2]);
            ViewBag.valor34 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1004].ItemArray[2]);
            ViewBag.valor35 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1035].ItemArray[2]);
            ViewBag.valor36 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1065].ItemArray[2]);
            ViewBag.valor37 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1096].ItemArray[2]);
            ViewBag.valor38 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1127].ItemArray[2]);
            ViewBag.valor39 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1155].ItemArray[2]);
            ViewBag.valor40 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1186].ItemArray[2]);
            ViewBag.valor41 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1216].ItemArray[2]);
            ViewBag.valor42 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1247].ItemArray[2]);
            ViewBag.valor43 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1277].ItemArray[2]);
            ViewBag.valor44 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1308].ItemArray[2]);
            ViewBag.valor45 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1339].ItemArray[2]);
            ViewBag.valor46 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1369].ItemArray[2]);
            ViewBag.valor47 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1400].ItemArray[2]);
            ViewBag.valor48 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1430].ItemArray[2]);
            ViewBag.valor49 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1461].ItemArray[2]);
            ViewBag.valor50 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1492].ItemArray[2]);
            ViewBag.valor51 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1520].ItemArray[2]);
            ViewBag.valor52 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1551].ItemArray[2]);
            ViewBag.valor53 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1581].ItemArray[2]);
            ViewBag.valor54 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1612].ItemArray[2]);
            ViewBag.valor55 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1642].ItemArray[2]);
            ViewBag.valor56 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1673].ItemArray[2]);
            ViewBag.valor57 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1704].ItemArray[2]);
            ViewBag.valor58 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1734].ItemArray[2]);
            ViewBag.valor59 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1765].ItemArray[2]);
            ViewBag.valor60 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1795].ItemArray[2]);
            ViewBag.valor61 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1826].ItemArray[2]);
            ViewBag.valor62 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1857].ItemArray[2]);
            ViewBag.valor63 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1885].ItemArray[2]);
            return View();
        }
    }
}

Indicadores-Economicos/Indicadores-Economicos/Controllers/InformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Indicadores_Economicos.Controllers
{
    public class InformationController : Controller
    {
        // GET: Information
        public ActionResult Information()
        {
            return View();
        }
    }
}

Indicadores-Economicos/Indicadores-Economicos/Controllers/VentaDolarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace Indicadores_Economicos.Controllers
{
    public class VentaDolarController : Controller
    {

        // GET: IndiEco
        public ActionResult Index()
        {
            /*cr.fi.bccr.gee.wsIndicadoresEconomicos cliente = new cr.fi.bccr.gee.wsIndicadoresEconomicos();
            DataSet tipoCambioVenta = cliente.ObtenerIndicadoresEconomicos("318","15/01/2014","15/03/2019","Felipe Ramirez","N");
            //ViewBag.indicador = "Código indicador: " + tipoCambioVenta.Tables[0].Rows[0].ItemArray[0].ToString();
            //ViewBag.fecha = "Fecha consultada: " + tipoCambioVenta.Tables[0].Rows[0].ItemArray[1].ToString();
            ViewBag.valor = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[0].ItemArray[2]);
            ViewBag.valor2 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[31].ItemArray[2]);
            ViewBag.valor3 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[59].ItemArray[2]);
            ViewBag.valor4 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[90].ItemArray[2]);
            ViewBag.valor5 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[120].ItemArray[2]);
            ViewBag.valor6 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[151].ItemArray[2]);
            ViewBag.valor7 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[181].ItemArray[2]); 
            ViewBag.valor8 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[212].ItemArray[2]); 
            ViewBag.valor9 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[243].ItemArray[2]); 
            ViewBag.valor10 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[273].ItemArray[2]);
            ViewBag.valor11 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[304].ItemArray[2]);
            ViewBag.valor12 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[334].ItemArray[2]);
            ViewBag.valor13 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[365].ItemArray[2]);
            ViewBag.valor14 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[396].ItemArray[2]);
            ViewBag.valor15 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[424].ItemArray[2]);
            ViewBag.valor16 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[455].ItemArray[2]);
            ViewBag.valor17 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[485].ItemArray[2]);
            ViewBag.valor18 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[516].ItemArray[2]);
            ViewBag.valor19 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[546].ItemArray[2]);
            ViewBag.valor20 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[577].ItemArray[2]);
            ViewBag.valor21 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[608].ItemArray[2]);
            ViewBag.valor22 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[638].ItemArray[2]);
            ViewBag.valor23 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[669].ItemArray[2]);
            ViewBag.valor24 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[699].ItemArray[2]);
            ViewBag.valor25 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[730].ItemArray[2]);
            ViewBag.valor26 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[761].ItemArray[2]);
            ViewBag.valor27 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[790].ItemArray[2]);
            ViewBag.valor28 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[821].ItemArray[2]);
            ViewBag.valor29 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[851].ItemArray[2]);
            ViewBag.valor30 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[882].ItemArray[2]);
            ViewBag.valor31 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[912].ItemArray[2]);
            ViewBag.valor32 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[943].ItemArray[2]);
            ViewBag.valor33 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[974].ItemArray[2]);
            ViewBag.valor34 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1004].ItemArray[2]);
            ViewBag.valor35 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1035].ItemArray[2]);
            ViewBag.valor36 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1065].ItemArray[2]);
            ViewBag.valor37 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1096].ItemArray[2]);
            ViewBag.valor38 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1127].ItemArray[2]);
            ViewBag.valor39 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1155].ItemArray[2]);
            ViewBag.valor40 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1186].ItemArray[2]);
            ViewBag.valor41 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1216].ItemArray[2]);
            ViewBag.valor42 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1247].ItemArray[2]);
            ViewBag.valor43 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1277].ItemArray[2]);
            ViewBag.valor44 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1308].ItemArray[2]);
            ViewBag.valor45 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1339].ItemArray[2]);
            ViewBag.valor46 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1369].ItemArray[2]);
            ViewBag.valor47 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1400].ItemArray[2]);
            ViewBag.valor48 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1430].ItemArray[2]);
            ViewBag.valor49 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1461].ItemArray[2]);
            ViewBag.valor50 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1492].ItemArray[2]);
            ViewBag.valor51 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1520].ItemArray[2]);
            ViewBag.valor52 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1551].ItemArray[2]);
            ViewBag.valor53 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1581].ItemArray[2]);
            ViewBag.valor54 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1612].ItemArray[2]);
            ViewBag.valor55 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1642].ItemArray[2]);
            ViewBag.valor56 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1673].ItemArray[2]);
            ViewBag.valor57 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1704].ItemArray[2]);
            ViewBag.valor58 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1734].ItemArray[2]);
            ViewBag.valor59 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1765].ItemArray[2]);
            ViewBag.valor60 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1795].ItemArray[2]);
            ViewBag.valor61 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1826].ItemArray[2]);
            ViewBag.valor62 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1857].ItemArray[2]);
            ViewBag.valor63 = Convert.ToInt32(tipoCambioVenta.Tables[0].Rows[1885].ItemArray[2]);*/
            ViewBag.salida = obtenerDatos(); 
            return View();
        }


        public string obtenerDatos()
        {
            SqlConnection conexionSQL = new SqlConnection("Data Source=.;Initial Catalog=Indicadores;Integrated Security=True");
            SqlCommand cmd = new SqlCommand();
            cmd.CommandText = "select fecha, valor from VentaDolar";
            cmd.CommandType = CommandType.Text;
            cmd.Connection = conexionSQL;
            conexionSQL.Open();

            DataTable datos = new DataTable();
            datos.Load(cmd.ExecuteReader());
            conexionSQL.Close();

            string strDatos;

            strDatos = "[['task', Hours per Day],";

            foreach (DataRow dr in datos.Rows)
            {
                strDatos = strDatos + "[";
                strDatos = strDatos + "'" + dr[0] + "'" + "," + dr[1];
                strDatos = strDatos + "],";
            }
            strDatos = strDatos + "]";
            return strDatos;
        }

    }
}

Indicadores-Economicos/Indicadores-Economicos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Indicadores Economicos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
            <a class="navbar-brand" href="#">
                <img src="~/Content/assets/logo.png" width="30" height="30" class="d-inline-block align-top" alt="" id="sidebarCollapse">
                Indicadores Economicos
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    @Html.ActionLink("Inicio", "Index", "Home", new { @class = "nav-item nav-link" })
                    <a class="nav-item nav-link" href="http://localhost:50371/Information/Information">Informacion</a>
                    @Html.ActionLink("Foro", "Index", "Blog", new { @class = "nav-item nav-link" })
                </div>
            </div>
            <button class="btn btn-success"><a class="nav-item nav-link  text-white" href="http://localhost:50371/suscripcion/create">Suscribirme</a></button>

        </nav>
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Indicadores Economicos</h3>
            </div>
            <ul class="list-unstyled components">
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Inicio</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            @Html.ActionLink("Home", "Index", "Home")
                        </li>
                        <li>
                            @Html.ActionLink("Foro", "Information", "Information")
                        </li>
                        <li>
                            @Html.ActionLink("Suscribirme", "create", "Suscripcion")
                        </li>
                    </ul>
                </li>

                <li>
                    @Html.ActionLink("Sobre", "Information", "Information")
                </li>
                <li>
                    @Html.ActionLink("Servicios", "Index", "Home")
                </li>
                <li>
                    <a href="#IndiSub" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Indicador</a>
                    <ul class="collapse list-unstyled" id="IndiSub">
                        <li>
                            @Html.ActionLink("Tasa de Politica Monetaria", "Index", "TasaMonetaria")
                        </li>
                        <li>
                            @Html.ActionLink("Tasa Basica Pasiva", "Index", "BasicaPasiva")
                        </li>
                        <li>
                            @Html.ActionLink("Compra del dólar", "Index", "CompraDolar")
                        </li>
                        <li>
                            @Html.ActionLink("Venta del dólar", "Index", "VentaDolar")
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>




        <div class="container body-content">
            <div class=" mt-5">
                @RenderBody()
            </div>
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Kenny Cardenas Reyes, Felipe Vargas Ramirez</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
    <script type="text/javascript">
        $('#myModal').modal('show');
    </script>
</body>
</html>